In [1]:
import tensorflow as tf

In [3]:
print(tf.__version__)

2.11.0


In [6]:
a=tf.ones((2,2))

In [7]:
b=tf.zeros((2,2))

In [14]:
tf.matmul(a,b)
tf.fill((2,2),40)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[40, 40],
       [40, 40]])>

In [15]:
tf.constant("Hello",name='x')

<tf.Tensor: shape=(), dtype=string, numpy=b'Hello'>

In [18]:
print(tf.zeros(10))

tf.Tensor([0. 0. 0. 0. 0. 0. 0. 0. 0. 0.], shape=(10,), dtype=float32)
